#!/usr/bin/env sh
#
# tun-on.sh — start the system-wide TUN proxy on this Omarchy machine.
# Upstream is read from the proxy-on.sh configuration, so if you use
#   source proxy-on.sh --address HOST:PORT
# this script automatically follows the same address.
#
# Codex/OpenAI and DeepSeek connections stay DIRECT and never enter the TUN.

MihomoBin="${MihomoBin:-$HOME/.local/bin/mihomo}"
CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/mihomo"
CFG_FILE="$CFG_DIR/config.yaml"
ENVFILE="${XDG_CONFIG_HOME:-$HOME/.config}/environment.d/proxy.conf"
UNIT="mihomo-tun"

die() {
    echo "错误: $*" >&2
    exit 1
}

[ -x "$MihomoBin" ] || die "没有找到 mihomo，请先安装到 $MihomoBin"
[ -f "$ENVFILE" ] || die "没有找到代理配置 $ENVFILE，请先执行: source proxy-on.sh --address 地址:端口"

PROXY_HTTP=$(sed -n 's/^http_proxy=http:\/\///p' "$ENVFILE" | head -n1)
[ -n "$PROXY_HTTP" ] || die "代理配置里缺少 http_proxy"
UPSTREAM_HOST=${PROXY_HTTP%:*}
UPSTREAM_PORT=${PROXY_HTTP##*:}
case "$UPSTREAM_PORT" in
    ''|*[!0-9]*) die "代理配置里的端口无效: $UPSTREAM_PORT" ;;
esac

mkdir -p "$CFG_DIR"

# ---------------------------------------------------------------------------
# Write the mihomo TUN config.
# Codex (OpenAI) and DeepSeek are pinned to DIRECT so TUN can never cut them.
# ---------------------------------------------------------------------------
cat > "$CFG_FILE" <<EOF
# Generated by tun-on.sh — do not edit by hand.
# Upstream: $UPSTREAM_HOST:$UPSTREAM_PORT (from proxy-on.sh)

mixed-port: 0
allow-lan: false
bind-address: "*"
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]

tun:
  enable: true
  stack: gvisor
  mtu: 1500
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 127.0.0.1:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fake-ip-filter:
    - "*.openai.com"
    - "*.chatgpt.com"
    - "*.chatgpt.site"
    - "*.chatgpt-team.site"
    - "*.oaistatic.com"
    - "*.oaiusercontent.com"
    - "*.deepseek.com"
    - "*.lan"
    - "*.local"
    - localhost

proxies:
  - name: upstream
    type: socks5
    server: $UPSTREAM_HOST
    port: $UPSTREAM_PORT
    udp: true

proxy-groups:
  - name: GLOBAL
    type: select
    proxies:
      - upstream

rules:
  # Codex / OpenAI — always direct
  - DOMAIN-SUFFIX,openai.com,DIRECT
  - DOMAIN-SUFFIX,chatgpt.com,DIRECT
  - DOMAIN-SUFFIX,chatgpt.site,DIRECT
  - DOMAIN-SUFFIX,chatgpt-team.site,DIRECT
  - DOMAIN-SUFFIX,oaistatic.com,DIRECT
  - DOMAIN-SUFFIX,oaiusercontent.com,DIRECT
  # DeepSeek — always direct
  - DOMAIN-SUFFIX,deepseek.com,DIRECT
  # Keep time sync and LAN local
  - DOMAIN-SUFFIX,pool.ntp.org,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  # Everything else goes through the upstream proxy
  - MATCH,GLOBAL
EOF

echo "正在验证 mihomo 配置..."
"$MihomoBin" -t -f "$CFG_FILE" >/dev/null 2>&1 || die "mihomo 配置测试失败"

systemctl --user daemon-reload >/dev/null 2>&1
systemctl --user enable --now "$UNIT" >/dev/null 2>&1 || die "启动 mihomo-tun 服务失败"

echo "TUN 代理已开启"
echo "  上游: socks5://$UPSTREAM_HOST:$UPSTREAM_PORT"
echo "  Codex/OpenAI 与 DeepSeek: 直连（不受 TUN 影响）"
echo "  关闭请运行: ./tun-off.sh"
