#!/usr/bin/env sh
#
# tun-off.sh — stop the system-wide TUN proxy and remove its autostart.

systemctl --user disable --now mihomo-tun.service >/dev/null 2>&1
sleep 2

if systemctl --user is-active --quiet mihomo-tun.service; then
    echo "TUN 服务仍在运行，请稍后重试"
    exit 1
fi

# Remove the generated config and runtime cache so "off" leaves nothing
# behind. tun-on.sh rebuilds both on demand.
CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/mihomo"
CFG_FILE="$CFG_DIR/config.yaml"
if [ -f "$CFG_FILE" ] && grep -q '^# Generated by tun-on.sh' "$CFG_FILE" 2>/dev/null; then
    rm -f "$CFG_FILE" "$CFG_DIR/cache.db"
    rmdir "$CFG_DIR" 2>/dev/null || true
fi

echo "TUN 代理已关闭"
echo "  网络已恢复为直连（可用 proxy-on.sh 继续使用应用级代理）"
if ip -br link show 2>/dev/null | grep -qi '\bMeta\b'; then
    echo "  提示: 虚拟网卡 Meta 仍存在，几秒后会自动消失"
fi
