#!/usr/bin/env sh
#
# tun-on.sh — start the system-wide TUN proxy on this Omarchy machine.
# Upstream can be passed directly or read from the proxyctl/proxy-on.sh
# configuration:
#   ./tun-on.sh --address HOST:PORT
#   ./tun-on.sh --host HOST --port PORT
#   ./tun-on.sh            # uses PROXY_HOST/PROXY_PORT or environment.d
#
# OpenAI/ChatGPT follow the upstream proxy by default; DeepSeek stays DIRECT.
# Use --openai-direct to restore the old OpenAI/ChatGPT DIRECT protection.

MihomoBin="${MihomoBin:-$HOME/.local/bin/mihomo}"
CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/mihomo"
CFG_FILE="$CFG_DIR/config.yaml"
ENVFILE="${XDG_CONFIG_HOME:-$HOME/.config}/environment.d/proxy.conf"
UNIT="mihomo-tun"
OPENAI_DIRECT="${OPENAI_DIRECT:-0}"

die() {
    echo "错误: $*" >&2
    exit 1
}

usage() {
    echo "用法: ./tun-on.sh [options]"
    echo "  -a, --address HOST:PORT   上游代理地址（缺省读环境文件/PROXY_HOST/PROXY_PORT）"
    echo "  -H, --host HOST           上游代理主机"
    echo "  -P, --port PORT           上游代理端口"
    echo "      --openai-direct       让 OpenAI/ChatGPT 走 DIRECT 直连（默认走上游代理）"
    echo "  -h, --help                显示帮助"
}

[ -x "$MihomoBin" ] || die "没有找到 mihomo，请先安装到 $MihomoBin"

ARG_ADDRESS=""
ARG_HOST=""
ARG_PORT=""
while [ "$#" -gt 0 ]; do
    case "$1" in
        -a|--address)
            [ "$#" -ge 2 ] || die "$1 需要参数（用法见 --help）"
            ARG_ADDRESS="$2"
            shift 2
            ;;
        -H|--host)
            [ "$#" -ge 2 ] || die "$1 需要参数（用法见 --help）"
            ARG_HOST="$2"
            shift 2
            ;;
        -P|--port)
            [ "$#" -ge 2 ] || die "$1 需要参数（用法见 --help）"
            ARG_PORT="$2"
            shift 2
            ;;
        --openai-direct)
            OPENAI_DIRECT=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            die "未知参数: $1（用法见 --help）"
            ;;
    esac
done

# 显式 --address 拆分 host/port
if [ -n "$ARG_ADDRESS" ]; then
    case "$ARG_ADDRESS" in
        *:*)
            ARG_HOST="${ARG_ADDRESS%:*}"
            ARG_PORT="${ARG_ADDRESS##*:}"
            ;;
        *)
            ARG_HOST="$ARG_ADDRESS"
            ;;
    esac
fi

# 未显式指定时，读取 proxyctl 写入的会话环境文件作为上游
FILE_HOST=""
FILE_PORT=""
if [ -f "$ENVFILE" ]; then
    PROXY_HTTP=$(sed -n 's/^http_proxy=http:\/\///p' "$ENVFILE" | head -n1)
    if [ -n "$PROXY_HTTP" ]; then
        FILE_HOST=${PROXY_HTTP%:*}
        FILE_PORT=${PROXY_HTTP##*:}
    fi
fi

UPSTREAM_HOST="${ARG_HOST:-${FILE_HOST:-${PROXY_HOST:-}}}"
UPSTREAM_PORT="${ARG_PORT:-${FILE_PORT:-${PROXY_PORT:-}}}"
if [ -z "$UPSTREAM_HOST" ]; then
    die "缺少上游代理地址。请用 --address HOST:PORT，或先执行: source proxy-on.sh --address 地址:端口"
fi
if [ -z "$UPSTREAM_PORT" ]; then
    die "缺少上游代理端口。请用 --address HOST:PORT 或 --port PORT"
fi
case "$UPSTREAM_PORT" in
    *[!0-9]*) die "代理配置里的端口无效: $UPSTREAM_PORT" ;;
esac

mkdir -p "$CFG_DIR"

# ---------------------------------------------------------------------------
# Write the mihomo TUN config.
# Default: OpenAI/ChatGPT go through the upstream proxy; DeepSeek stays DIRECT.
# ---------------------------------------------------------------------------
if [ "$OPENAI_DIRECT" = "1" ]; then
    OPENAI_FILTER='    - "*.openai.com"
    - "*.chatgpt.com"
    - "*.chatgpt.site"
    - "*.chatgpt-team.site"
    - "*.oaistatic.com"
    - "*.oaiusercontent.com"
'
    OPENAI_RULES='  # Codex / OpenAI — always direct (--openai-direct)
  - DOMAIN-SUFFIX,openai.com,DIRECT
  - DOMAIN-SUFFIX,chatgpt.com,DIRECT
  - DOMAIN-SUFFIX,chatgpt.site,DIRECT
  - DOMAIN-SUFFIX,chatgpt-team.site,DIRECT
  - DOMAIN-SUFFIX,oaistatic.com,DIRECT
  - DOMAIN-SUFFIX,oaiusercontent.com,DIRECT
'
else
    OPENAI_FILTER=""
    OPENAI_RULES='  # OpenAI/ChatGPT follow the upstream proxy (default)'
fi

cat > "$CFG_FILE" <<EOF
# Generated by tun-on.sh — do not edit by hand.
# Upstream: $UPSTREAM_HOST:$UPSTREAM_PORT (from --address / proxy-on.sh)

mixed-port: 0
allow-lan: false
bind-address: "*"
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]

tun:
  enable: true
  stack: gvisor
  mtu: 1500
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 127.0.0.1:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fake-ip-filter:
$OPENAI_FILTER
    - "*.deepseek.com"
    - "*.lan"
    - "*.local"
    - localhost

proxies:
  - name: upstream
    type: socks5
    server: $UPSTREAM_HOST
    port: $UPSTREAM_PORT
    udp: true

proxy-groups:
  - name: GLOBAL
    type: select
    proxies:
      - upstream

rules:
$OPENAI_RULES
  # DeepSeek — always direct
  - DOMAIN-SUFFIX,deepseek.com,DIRECT
  # Keep time sync and LAN local
  - DOMAIN-SUFFIX,pool.ntp.org,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  # Everything else goes through the upstream proxy
  - MATCH,GLOBAL
EOF

echo "正在验证 mihomo 配置..."
"$MihomoBin" -t -f "$CFG_FILE" >/dev/null 2>&1 || die "mihomo 配置测试失败"

systemctl --user daemon-reload >/dev/null 2>&1
systemctl --user enable --now "$UNIT" >/dev/null 2>&1 || die "启动 mihomo-tun 服务失败"

echo "TUN 代理已开启"
echo "  上游: socks5://$UPSTREAM_HOST:$UPSTREAM_PORT"
if [ "$OPENAI_DIRECT" = "1" ]; then
    echo "  OpenAI/ChatGPT 与 DeepSeek: 直连（不受 TUN 影响）"
else
    echo "  OpenAI/ChatGPT: 走上游代理"
    echo "  DeepSeek: 直连（不受 TUN 影响）"
fi
echo "  关闭请运行: ./tun-off.sh"
