//go:build linux

package tun

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const (
	unitName = "mihomo-tun.service"

	configMarker = "# Generated by proxyctl tun. Do not edit by hand."
	legacyMarker = "# Generated by tun-on.sh"
)

// configDir 返回 mihomo 配置目录（~/.config/mihomo）。
func configDir() string {
	return filepath.Join(configHome(), "mihomo")
}

// configPath 返回 mihomo TUN 配置文件路径。
func configPath() string {
	return filepath.Join(configDir(), "config.yaml")
}

// configHome 返回 XDG 配置目录，未设置时回退 ~/.config。
func configHome() string {
	if d := os.Getenv("XDG_CONFIG_HOME"); d != "" {
		return d
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return ".config"
	}
	return filepath.Join(home, ".config")
}

// findMihomo 定位 mihomo：MIHOMO_BIN > PATH > ~/.local/bin。
func findMihomo() (string, error) {
	if p := strings.TrimSpace(os.Getenv("MIHOMO_BIN")); p != "" {
		if isExecutable(p) {
			return p, nil
		}
		return "", fmt.Errorf("MIHOMO_BIN 指向的文件不可执行: %s", p)
	}
	if p, err := exec.LookPath("mihomo"); err == nil {
		return p, nil
	}
	home, err := os.UserHomeDir()
	if err == nil {
		p := filepath.Join(home, ".local", "bin", "mihomo")
		if isExecutable(p) {
			return p, nil
		}
	}
	return "", errors.New("没有找到 mihomo：请安装到 PATH 或设置 MIHOMO_BIN")
}

func isExecutable(p string) bool {
	info, err := os.Stat(p)
	return err == nil && !info.IsDir() && info.Mode()&0o111 != 0
}

// openaiFakeFilterLines 是 OpenAI/ChatGPT 域名在 fake-ip-filter 中的直连
// DNS 行（仅在 --openai-direct 时写入）。
const openaiFakeFilterLines = `    - "*.openai.com"
    - "*.chatgpt.com"
    - "*.chatgpt.site"
    - "*.chatgpt-team.site"
    - "*.oaistatic.com"
    - "*.oaiusercontent.com"
`

// openaiDirectRuleLines 是 OpenAI/ChatGPT 域名走 DIRECT 的规则行
// （仅在 --openai-direct 时写入）。
const openaiDirectRuleLines = `  # Codex / OpenAI — always direct (--openai-direct)
  - DOMAIN-SUFFIX,openai.com,DIRECT
  - DOMAIN-SUFFIX,chatgpt.com,DIRECT
  - DOMAIN-SUFFIX,chatgpt.site,DIRECT
  - DOMAIN-SUFFIX,chatgpt-team.site,DIRECT
  - DOMAIN-SUFFIX,oaistatic.com,DIRECT
  - DOMAIN-SUFFIX,oaiusercontent.com,DIRECT
`

// renderConfig 生成受管 mihomo TUN 配置。
// openaiDirect 为 true 时保留 OpenAI/ChatGPT 直连保护；默认 false 让这些
// 域名跟随上游代理（DeepSeek 与 NTP 始终 DIRECT）。
func renderConfig(host, port string, openaiDirect bool) string {
	filter, rules := "", ""
	if openaiDirect {
		filter = openaiFakeFilterLines
		rules = openaiDirectRuleLines
	} else {
		rules = "  # OpenAI/ChatGPT follow the upstream proxy (default)\n"
	}
	return fmt.Sprintf(`%s
# Upstream: %s:%s (socks5)

mixed-port: 0
allow-lan: false
bind-address: "*"
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]

tun:
  enable: true
  stack: gvisor
  mtu: 1500
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 127.0.0.1:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fake-ip-filter:
%s
    - "*.deepseek.com"
    - "*.lan"
    - "*.local"
    - localhost

proxies:
  - name: upstream
    type: socks5
    server: %s
    port: %s
    udp: true

proxy-groups:
  - name: GLOBAL
    type: select
    proxies:
      - upstream

rules:
%s
  # DeepSeek — always direct
  - DOMAIN-SUFFIX,deepseek.com,DIRECT
  # Keep time sync and LAN local
  - DOMAIN-SUFFIX,pool.ntp.org,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  # Everything else goes through the upstream proxy
  - MATCH,GLOBAL
`, configMarker, host, port, filter, host, port, rules)
}

// On 写配置、校验并启动 mihomo TUN 用户服务。
func On(host, port string, openaiDirect bool) error {
	mihomo, err := findMihomo()
	if err != nil {
		return err
	}

	cfg := configPath()
	if err := os.MkdirAll(filepath.Dir(cfg), 0o755); err != nil {
		return err
	}
	if err := writeFileAtomic(cfg, renderConfig(host, port, openaiDirect), 0o644); err != nil {
		return fmt.Errorf("写入 mihomo 配置失败: %w", err)
	}
	if out, err := exec.Command(mihomo, "-t", "-f", cfg).CombinedOutput(); err != nil {
		return fmt.Errorf("mihomo 配置测试失败: %w（%s）", err, strings.TrimSpace(string(out)))
	}

	if _, err := exec.LookPath("systemctl"); err != nil {
		return errors.New("未找到 systemctl，无法启动 mihomo-tun 用户服务")
	}
	if err := ensureUnit(mihomo); err != nil {
		return err
	}
	if err := exec.Command("systemctl", "--user", "daemon-reload").Run(); err != nil {
		return fmt.Errorf("systemctl daemon-reload 失败: %w", err)
	}
	if out, err := exec.Command("systemctl", "--user", "enable", "--now", unitName).CombinedOutput(); err != nil {
		return fmt.Errorf("启动 mihomo-tun 服务失败: %w（%s）", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// Off 停止并禁用服务，然后清理受管配置与运行时缓存。
func Off() error {
	var errs []error
	if _, err := exec.LookPath("systemctl"); err == nil {
		if out, err := exec.Command("systemctl", "--user", "disable", "--now", unitName).CombinedOutput(); err != nil {
			errs = append(errs, fmt.Errorf("停止 mihomo-tun 服务失败: %w（%s）", err, strings.TrimSpace(string(out))))
		}
		// 等待服务真正退出（虚拟网卡需要一点时间消失）。
		for i := 0; i < 25; i++ {
			if err := exec.Command("systemctl", "--user", "is-active", "--quiet", unitName).Run(); err != nil {
				break
			}
			time.Sleep(200 * time.Millisecond)
		}
	}

	if err := removeManagedConfig(); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// ReadStatus 读取 mihomo TUN 当前状态（只读）。
func ReadStatus() (Status, error) {
	st := Status{Service: "stopped", ConfigPath: configPath()}
	if _, err := exec.LookPath("systemctl"); err != nil {
		st.Service = "systemctl 不可用"
	} else if err := exec.Command("systemctl", "--user", "is-active", "--quiet", unitName).Run(); err == nil {
		st.Service = "running"
	}

	if data, err := os.ReadFile(configPath()); err == nil {
		st.ConfigExists = true
		host, port, protected := parseConfig(string(data))
		if host != "" && port != "" {
			st.Upstream = host + ":" + port
		}
		st.Protected = protected
	}
	st.Interfaces = metaInterfaces()
	return st, nil
}

// parseConfig 从受管配置中提取上游 host/port 与 DIRECT 保护域名。
func parseConfig(content string) (host, port string, protected []string) {
	scanner := bufio.NewScanner(strings.NewReader(content))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		switch {
		case strings.HasPrefix(line, "server:"):
			host = strings.TrimSpace(strings.TrimPrefix(line, "server:"))
		case strings.HasPrefix(line, "port:"):
			port = strings.TrimSpace(strings.TrimPrefix(line, "port:"))
		case strings.Contains(line, "DOMAIN-SUFFIX") && strings.Contains(line, "DIRECT"):
			if parts := strings.Split(line, ","); len(parts) >= 3 {
				protected = append(protected, parts[1])
			}
		}
	}
	return host, port, protected
}

// ensureUnit 在 ~/.config/systemd/user/mihomo-tun.service 缺失时创建用户单元。
func ensureUnit(mihomoBin string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("获取用户主目录失败: %w", err)
	}
	unitPath := filepath.Join(home, ".config", "systemd", "user", unitName)
	if _, err := os.Stat(unitPath); err == nil {
		return nil
	}
	content := fmt.Sprintf(`[Unit]
Description=mihomo TUN proxy client (managed by proxyctl)
After=default.target

[Service]
ExecStart=%s -f %s
Restart=on-failure
RestartSec=3
LimitNOFILE=1048576

[Install]
WantedBy=default.target
`, mihomoBin, configPath())
	if err := writeFileAtomic(unitPath, content, 0o644); err != nil {
		return fmt.Errorf("创建 %s 失败: %w", unitPath, err)
	}
	return nil
}

// removeManagedConfig 删除由 proxyctl/tun-on.sh 生成的配置与缓存。
func removeManagedConfig() error {
	cfg := configPath()
	data, err := os.ReadFile(cfg)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	text := string(data)
	if !strings.Contains(text, configMarker) && !strings.Contains(text, legacyMarker) {
		return nil // 用户自建配置不删除
	}
	if err := os.Remove(cfg); err != nil && !os.IsNotExist(err) {
		return err
	}
	_ = os.Remove(filepath.Join(configDir(), "cache.db"))
	_ = os.Remove(configDir())
	return nil
}

// metaInterfaces 返回名字包含 Meta 的网络接口（mihomo TUN 默认网卡名）。
func metaInterfaces() []string {
	if _, err := exec.LookPath("ip"); err != nil {
		return nil
	}
	out, err := exec.Command("ip", "-br", "link").Output()
	if err != nil {
		return nil
	}
	var ifaces []string
	for _, line := range strings.Split(string(out), "\n") {
		if fields := strings.Fields(line); len(fields) > 0 && strings.Contains(strings.ToLower(fields[0]), "meta") {
			ifaces = append(ifaces, fields[0])
		}
	}
	return ifaces
}

// writeFileAtomic 原子写入文件。
func writeFileAtomic(path, content string, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".proxyctl-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	cleanup := func() {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
	}
	if err := tmp.Chmod(perm); err != nil {
		cleanup()
		return err
	}
	if _, err := tmp.WriteString(content); err != nil {
		cleanup()
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	return nil
}
