//go:build linux

package proxy

// Linux 系统代理后端。
//
// Linux 桌面没有统一的“系统代理”概念，因此本后端把 proxyctl 的
// 系统代理实现为 Omarchy / GNOME 桌面实际生效的几层：
//
//  1. GNOME gsettings（org.gnome.system.proxy）——Chromium 等走
//     GNOME 代理设置的桌面应用；
//  2. ~/.config/environment.d/proxy.conf + systemd --user / D-Bus——
//     桌面会话启动的应用所继承的环境变量；
//  3. ~/.config/chromium-flags.conf 与 chrome-flags.conf——Chromium /
//     Chrome 启动参数（--proxy-server）。
//
// 这三层与仓库内 proxy-on.sh / proxy-off.sh 的行为一一对应，proxyctl
// 只是把脚本逻辑移植为 Go，并在此基础上提供快照、恢复与 profile。

import (
	"errors"
	"fmt"
	"net"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	gsettingsSchema = "org.gnome.system.proxy"

	sessionEnvDirName  = "environment.d"
	sessionEnvFileName = "proxy.conf"

	// sessionEnvMarker 标记 proxyctl 管理的会话环境文件；其余行可手动追加，
	// 但关闭时该文件会被整体删除（与旧 proxy-on.sh 行为一致）。
	sessionEnvMarker = "# Generated by proxyctl. Use proxyctl on/off/restore to change."

	defaultNoProxy = "localhost,127.0.0.1,::1"

	proxyFlagPrefix = "--proxy-server="
)

// sessionEnvVarNames 是会话环境文件与 systemd/D-Bus 中受管的全部变量名。
var sessionEnvVarNames = []string{
	"http_proxy", "https_proxy", "ftp_proxy",
	"HTTP_PROXY", "HTTPS_PROXY", "FTP_PROXY",
	"all_proxy", "ALL_PROXY",
	"no_proxy", "NO_PROXY",
}

// chromiumFlagFiles 返回 Chromium / Chrome 启动参数文件路径。
func chromiumFlagFiles() []string {
	dir := configHome()
	return []string{
		filepath.Join(dir, "chromium-flags.conf"),
		filepath.Join(dir, "chrome-flags.conf"),
	}
}

// configHome 返回 XDG 配置目录，未设置时回退 ~/.config。
func configHome() string {
	if d := os.Getenv("XDG_CONFIG_HOME"); d != "" {
		return d
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return ".config"
	}
	return filepath.Join(home, ".config")
}

// sessionEnvPath 返回会话环境文件路径。
func sessionEnvPath() string {
	return filepath.Join(configHome(), sessionEnvDirName, sessionEnvFileName)
}

// ---------------------------------------------------------------------------
// 读取
// ---------------------------------------------------------------------------

// Get 读取 Linux 系统代理状态：优先 gsettings 桌面代理；若桌面代理未开启
// 而会话环境文件（由 proxyctl/旧脚本写入）仍存在，则以其为准。
func Get() (*Info, error) {
	info := infoFromDesktop(readDesktopSnapshot())
	if proxyEnabled(info) {
		return info, nil
	}
	if envInfo, ok := readSessionEnvInfo(); ok {
		return envInfo, nil
	}
	return info, nil
}

// readDesktopSnapshot 读取 gsettings 桌面代理完整状态；gsettings 不可用时
// 返回 nil（该层被跳过，不影响其他层）。
func readDesktopSnapshot() *LinuxDesktopSnapshot {
	if !gsettingsAvailable() {
		return nil
	}
	d := &LinuxDesktopSnapshot{}
	if raw, err := gsettingsGet(gsettingsSchema, "mode"); err == nil {
		d.Mode = parseGValue(raw)
	}
	d.HTTP = readGEndpoint("http")
	d.HTTPS = readGEndpoint("https")
	d.SOCKS = readGEndpoint("socks")
	if raw, err := gsettingsGet(gsettingsSchema, "autoconfig-url"); err == nil {
		if u := parseGValue(raw); u != "" {
			d.PAC = &PACState{Enabled: d.Mode == "auto", URL: u}
		}
	}
	if raw, err := gsettingsGet(gsettingsSchema, "ignore-hosts"); err == nil {
		d.IgnoreHosts = parseGStringList(raw)
	}
	return d
}

// readGEndpoint 读取某个协议（http/https/socks）的 host/port。
func readGEndpoint(kind string) *EndpointState {
	schema := gsettingsSchema + "." + kind
	rawHost, err := gsettingsGet(schema, "host")
	if err != nil {
		return nil
	}
	rawPort, _ := gsettingsGet(schema, "port")
	e := &EndpointState{
		Host: parseGValue(rawHost),
		Port: parseGValue(rawPort),
	}
	e.Enabled = e.Host != "" && e.Port != "" && e.Port != "0"
	return e
}

// infoFromDesktop 把桌面快照转换为 Info。
func infoFromDesktop(d *LinuxDesktopSnapshot) *Info {
	info := &Info{}
	if d == nil {
		return info
	}
	switch d.Mode {
	case "manual":
		if e := d.HTTP; e != nil && e.Enabled {
			info.HTTPEnable, info.HTTPHost, info.HTTPPort = true, e.Host, e.Port
		}
		if e := d.HTTPS; e != nil && e.Enabled {
			info.HTTPSEnable, info.HTTPSHost, info.HTTPSPort = true, e.Host, e.Port
		}
		if e := d.SOCKS; e != nil && e.Enabled {
			info.SOCKSEnable, info.SOCKSHost, info.SOCKSPort = true, e.Host, e.Port
		}
	case "auto":
		if d.PAC != nil && d.PAC.Enabled && d.PAC.URL != "" {
			info.AutoConfig = true
			info.AutoConfigURL = d.PAC.URL
		}
	}
	return info
}

// readSessionEnvInfo 解析受管会话环境文件并转换为 Info。
func readSessionEnvInfo() (*Info, bool) {
	data, err := os.ReadFile(sessionEnvPath())
	if err != nil || !isManagedEnvText(string(data)) {
		return nil, false
	}
	vals := parseEnvLines(string(data))
	info := &Info{}
	for _, name := range []string{"http_proxy", "https_proxy", "all_proxy", "HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY"} {
		raw := vals[name]
		if raw == "" {
			continue
		}
		scheme, host, port, ok := parseProxyEndpoint(raw)
		if !ok || host == "" {
			continue
		}
		switch scheme {
		case "http":
			info.HTTPEnable, info.HTTPHost, info.HTTPPort = true, host, port
			info.HTTPSEnable, info.HTTPSHost, info.HTTPSPort = true, host, port
		case "socks5", "socks5h", "socks":
			info.SOCKSEnable, info.SOCKSHost, info.SOCKSPort = true, host, port
		}
	}
	if !proxyEnabled(info) {
		return nil, false
	}
	return info, true
}

// proxyEnabled 报告 Info 中是否有任意一层代理已启用。
func proxyEnabled(info *Info) bool {
	return info != nil && (info.HTTPEnable || info.HTTPSEnable || info.SOCKSEnable || info.AutoConfig)
}

// parseEnvLines 解析 "KEY=VALUE" 形式的行。
func parseEnvLines(text string) map[string]string {
	out := make(map[string]string)
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if k, v, ok := strings.Cut(line, "="); ok {
			out[strings.TrimSpace(k)] = strings.TrimSpace(v)
		}
	}
	return out
}

// parseProxyEndpoint 解析 http://host:port / socks5h://host:port 形式 URL。
func parseProxyEndpoint(raw string) (scheme, host, port string, ok bool) {
	u, err := url.Parse(raw)
	if err != nil || u.Scheme == "" || u.Host == "" {
		return "", "", "", false
	}
	host, port = splitHostPort(u.Host)
	return u.Scheme, host, port, true
}

// splitHostPort 拆分 host:port（支持 [::1]:7890）。
func splitHostPort(hostport string) (host, port string) {
	if h, p, err := net.SplitHostPort(hostport); err == nil {
		return h, p
	}
	if i := strings.LastIndex(hostport, ":"); i >= 0 {
		return hostport[:i], hostport[i+1:]
	}
	return hostport, ""
}

// ---------------------------------------------------------------------------
// 写入
// ---------------------------------------------------------------------------

// ApplyProfile 把一组端点配置写入 Linux 桌面代理（gsettings、会话环境、
// Chromium flags）。全部端点均未启用时等价于 Clear。
func ApplyProfile(http, https, socks *EndpointState, pac *PACState) error {
	anyEndpoint := endpointEnabled(http) || endpointEnabled(https) || endpointEnabled(socks)
	pacEnabled := pac != nil && pac.Enabled && pac.URL != ""
	if !anyEndpoint && !pacEnabled {
		return Clear()
	}

	var errs []error
	if err := applyDesktopState(&LinuxDesktopSnapshot{
		Mode:  desktopMode(anyEndpoint, pacEnabled),
		HTTP:  http,
		HTTPS: https,
		SOCKS: socks,
		PAC:   pac,
	}); err != nil {
		errs = append(errs, fmt.Errorf("设置 GNOME 桌面代理失败: %w", err))
	}

	// 会话环境与 Chromium flags 只对可直接表达的 HTTP/SOCKS 端点有意义；
	// PAC 环境变量无法表达，交给 gsettings mode=auto。
	if vars := sessionEnvVars(http, socks); len(vars) > 0 {
		if err := writeSessionEnv(vars); err != nil {
			errs = append(errs, err)
		} else {
			importSessionEnv(vars)
		}
	} else {
		removeSessionEnv()
		unsetSessionEnv()
	}

	if u := desktopProxyFlagURL(http, socks); u != "" {
		if err := setBrowserProxyFlag(u); err != nil {
			errs = append(errs, fmt.Errorf("写入 Chromium/Chrome 启动参数失败: %w", err))
		}
	}
	return errors.Join(errs...)
}

// Clear 关闭 Linux 桌面代理：gsettings mode=none 并清空端点、删除受管会话
// 环境文件、从 systemd/D-Bus 移除变量、删除 Chromium/Chrome --proxy-server。
func Clear() error {
	var errs []error

	if err := removeSessionEnv(); err != nil {
		errs = append(errs, err)
	}
	unsetSessionEnv()

	if err := clearDesktopState(); err != nil {
		errs = append(errs, err)
	}
	if err := clearBrowserProxyFlags(); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// SnapshotSystem 保存 Linux 桌面代理完整状态（gsettings + 会话环境文件 +
// Chromium 文件是否存在），供 restore 恢复。
func SnapshotSystem() (SystemSnapshot, error) {
	snap := SystemSnapshot{Linux: &LinuxSnapshot{}}
	snap.Linux.Desktop = readDesktopSnapshot()

	if data, err := os.ReadFile(sessionEnvPath()); err == nil {
		snap.Linux.EnvFile = &LinuxEnvFileSnapshot{Existed: true, Content: string(data)}
	}
	chromium := make(map[string]bool)
	for _, p := range chromiumFlagFiles() {
		_, err := os.Stat(p)
		chromium[p] = err == nil
	}
	snap.Linux.Chromium = chromium
	return snap, nil
}

// RestoreSystem 从 Linux 快照恢复 gsettings、会话环境文件与 Chromium 文件。
func RestoreSystem(snap SystemSnapshot) error {
	if snap.Linux == nil {
		return nil
	}
	ls := snap.Linux
	var errs []error

	if ls.Desktop != nil {
		if err := applyDesktopState(ls.Desktop); err != nil {
			errs = append(errs, fmt.Errorf("恢复 GNOME 桌面代理失败: %w", err))
		}
	}
	if ls.EnvFile != nil && ls.EnvFile.Existed {
		if err := writeFileAtomic(sessionEnvPath(), ls.EnvFile.Content, 0o644); err != nil {
			errs = append(errs, err)
		}
	} else if err := removeSessionEnv(); err != nil {
		errs = append(errs, err)
	}
	for _, p := range chromiumFlagFiles() {
		existed := ls.Chromium != nil && ls.Chromium[p]
		if err := restoreBrowserFlagFile(p, existed); err != nil {
			errs = append(errs, err)
		}
	}
	syncSessionEnvAfterRestore()
	return errors.Join(errs...)
}

// ---------------------------------------------------------------------------
// GNOME gsettings
// ---------------------------------------------------------------------------

func gsettingsAvailable() bool {
	if _, err := exec.LookPath("gsettings"); err != nil {
		return false
	}
	_, err := exec.Command("gsettings", "get", gsettingsSchema, "mode").Output()
	return err == nil
}

func gsettingsGet(schema, key string) (string, error) {
	out, err := exec.Command("gsettings", "get", schema, key).Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

func gsettingsSet(schema, key, value string) error {
	return exec.Command("gsettings", "set", schema, key, value).Run()
}

// clearDesktopState 关闭桌面代理并清空 host/port（与旧 proxy-off.sh 一致）。
func clearDesktopState() error {
	if !gsettingsAvailable() {
		return nil
	}
	var errs []error
	for _, kind := range []string{"http", "https", "socks"} {
		if err := setGEndpoint(kind, nil); err != nil {
			errs = append(errs, err)
		}
	}
	if err := gsettingsSet(gsettingsSchema, "autoconfig-url", "''"); err != nil {
		errs = append(errs, err)
	}
	if err := gsettingsSet(gsettingsSchema, "mode", "'none'"); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// applyDesktopState 把快照/期望状态原样写入 gsettings（nil 端点视为关闭）。
func applyDesktopState(d *LinuxDesktopSnapshot) error {
	if !gsettingsAvailable() {
		return nil
	}
	var errs []error
	for kind, e := range map[string]*EndpointState{"http": d.HTTP, "https": d.HTTPS, "socks": d.SOCKS} {
		if err := setGEndpoint(kind, e); err != nil {
			errs = append(errs, err)
		}
	}
	if d.PAC != nil && d.PAC.Enabled && d.PAC.URL != "" {
		if err := gsettingsSet(gsettingsSchema, "autoconfig-url", gvalueString(d.PAC.URL)); err != nil {
			errs = append(errs, err)
		}
	} else if err := gsettingsSet(gsettingsSchema, "autoconfig-url", "''"); err != nil {
		errs = append(errs, err)
	}
	if len(d.IgnoreHosts) > 0 {
		if err := gsettingsSet(gsettingsSchema, "ignore-hosts", gvalueList(d.IgnoreHosts)); err != nil {
			errs = append(errs, err)
		}
	}
	mode := d.Mode
	if mode == "" {
		mode = desktopMode(endpointEnabled(d.HTTP) || endpointEnabled(d.HTTPS) || endpointEnabled(d.SOCKS), d.PAC != nil && d.PAC.Enabled && d.PAC.URL != "")
	}
	if err := gsettingsSet(gsettingsSchema, "mode", gvalueString(mode)); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// desktopMode 根据端点与 PAC 计算 gsettings mode。
func desktopMode(hasEndpoint, hasPAC bool) string {
	if hasPAC {
		return "auto"
	}
	if hasEndpoint {
		return "manual"
	}
	return "none"
}

// setGEndpoint 写入某个协议的 host/port；nil 或未启用的端点写入空值。
func setGEndpoint(kind string, e *EndpointState) error {
	schema := gsettingsSchema + "." + kind
	if e == nil || !e.Enabled || e.Host == "" || e.Port == "" {
		if err := gsettingsSet(schema, "host", "''"); err != nil {
			return err
		}
		return gsettingsSet(schema, "port", "0")
	}
	if err := gsettingsSet(schema, "host", gvalueString(e.Host)); err != nil {
		return err
	}
	return gsettingsSet(schema, "port", e.Port)
}

func endpointEnabled(e *EndpointState) bool {
	return e != nil && e.Enabled && e.Host != "" && e.Port != ""
}

// ---------------------------------------------------------------------------
// gsettings GVariant 文本解析
// ---------------------------------------------------------------------------

// parseGValue 解析 gsettings get 的简单 GVariant 文本：'string'、数字、
// ['a','b']。用于 host/port/mode 等标量。
func parseGValue(raw string) string {
	raw = strings.TrimSpace(raw)
	if len(raw) >= 2 && raw[0] == '\'' && raw[len(raw)-1] == '\'' {
		return raw[1 : len(raw)-1]
	}
	return raw
}

// parseGStringList 解析 gsettings get 的字符串数组文本，如
// ['localhost', '127.0.0.1', '::1']。
func parseGStringList(raw string) []string {
	raw = strings.TrimSpace(raw)
	if !strings.HasPrefix(raw, "[") || !strings.HasSuffix(raw, "]") {
		return nil
	}
	inner := strings.TrimSpace(raw[1 : len(raw)-1])
	if inner == "" {
		return nil
	}
	var out []string
	for _, item := range strings.Split(inner, ",") {
		if v := parseGValue(item); v != "" {
			out = append(out, v)
		}
	}
	return out
}

func gvalueString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `'`, `\'`)
	return "'" + s + "'"
}

func gvalueList(items []string) string {
	quoted := make([]string, 0, len(items))
	for _, s := range items {
		quoted = append(quoted, gvalueString(s))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// ---------------------------------------------------------------------------
// 会话环境文件 + systemd/D-Bus
// ---------------------------------------------------------------------------

// sessionEnvVars 根据端点生成会话环境变量；没有可表达端点时返回空 map。
func sessionEnvVars(http, socks *EndpointState) map[string]string {
	httpURL := endpointURL("http", http)
	socksURL := endpointURL("socks5h", socks)
	u := httpURL
	if u == "" {
		u = socksURL
	}
	if u == "" {
		return nil
	}
	all := socksURL
	if all == "" {
		all = u
	}
	noProxy := os.Getenv("PROXY_NO")
	if noProxy == "" {
		noProxy = defaultNoProxy
	}
	return map[string]string{
		"http_proxy":  u,
		"https_proxy": u,
		"ftp_proxy":   u,
		"HTTP_PROXY":  u,
		"HTTPS_PROXY": u,
		"FTP_PROXY":   u,
		"all_proxy":   all,
		"ALL_PROXY":   all,
		"no_proxy":    noProxy,
		"NO_PROXY":    noProxy,
	}
}

func endpointURL(scheme string, e *EndpointState) string {
	if !endpointEnabled(e) {
		return ""
	}
	return scheme + "://" + joinHostPort(e.Host, e.Port)
}

func joinHostPort(host, port string) string {
	if strings.Contains(host, ":") && !strings.HasPrefix(host, "[") {
		host = "[" + host + "]"
	}
	if port == "" {
		return host
	}
	return host + ":" + port
}

// renderEnvFileContent 生成受管会话环境文件内容。
func renderEnvFileContent(vars map[string]string) string {
	var b strings.Builder
	b.WriteString(sessionEnvMarker)
	b.WriteString("\n")
	for _, name := range sessionEnvVarNames {
		if v := vars[name]; v != "" {
			b.WriteString(name)
			b.WriteString("=")
			b.WriteString(v)
			b.WriteString("\n")
		}
	}
	return b.String()
}

func writeSessionEnv(vars map[string]string) error {
	return writeFileAtomic(sessionEnvPath(), renderEnvFileContent(vars), 0o644)
}

// removeSessionEnv 删除受 proxyctl/旧脚本管理的会话环境文件；其他文件保留。
func removeSessionEnv() error {
	data, err := os.ReadFile(sessionEnvPath())
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !isManagedEnvText(string(data)) {
		return nil
	}
	if err := os.Remove(sessionEnvPath()); err != nil && !os.IsNotExist(err) {
		return err
	}
	// 目录为空时顺手清理（不报错）。
	_ = os.Remove(filepath.Dir(sessionEnvPath()))
	return nil
}

// isManagedEnvText 判断文件是否由 proxyctl 或旧 proxy-on.sh 生成。
func isManagedEnvText(text string) bool {
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if !strings.HasPrefix(line, "#") {
			return false
		}
		return strings.Contains(line, "Generated by proxy") &&
			(strings.Contains(line, "proxy-on.sh") || strings.Contains(line, "proxyctl"))
	}
	return false
}

// importSessionEnv 把变量导入当前 systemd 用户会话与 D-Bus，使桌面启动的
// 应用立即继承（脚本原实现，静默失败）。
func importSessionEnv(vars map[string]string) {
	if len(vars) == 0 {
		unsetSessionEnv()
		return
	}
	pairs := envPairs(vars)
	if _, err := exec.LookPath("systemctl"); err == nil {
		cmd := exec.Command("systemctl", "--user", "import-environment")
		cmd.Args = append(cmd.Args, sessionEnvVarNames...)
		cmd.Env = envWith(os.Environ(), pairs)
		_ = cmd.Run()
	}
	if p, err := exec.LookPath("dbus-update-activation-environment"); err == nil {
		_ = exec.Command(p, pairs...).Run()
	}
}

// unsetSessionEnv 从 systemd 用户会话与 D-Bus 移除受管变量。
func unsetSessionEnv() {
	if _, err := exec.LookPath("systemctl"); err == nil {
		args := append([]string{"--user", "unset-environment"}, sessionEnvVarNames...)
		_ = exec.Command("systemctl", args...).Run()
	}
	if p, err := exec.LookPath("dbus-update-activation-environment"); err == nil {
		args := append([]string{"--unset"}, sessionEnvVarNames...)
		_ = exec.Command(p, args...).Run()
	}
}

// syncSessionEnvAfterRestore 恢复后按环境文件内容重新导入/移除会话变量。
func syncSessionEnvAfterRestore() {
	if info, ok := readSessionEnvInfo(); ok {
		importSessionEnv(sessionEnvVars(&EndpointState{Enabled: true, Host: info.HTTPHost, Port: info.HTTPPort},
			&EndpointState{Enabled: true, Host: info.SOCKSHost, Port: info.SOCKSPort}))
		return
	}
	unsetSessionEnv()
}

func envPairs(vars map[string]string) []string {
	out := make([]string, 0, len(vars))
	for _, name := range sessionEnvVarNames {
		if v := vars[name]; v != "" {
			out = append(out, name+"="+v)
		}
	}
	return out
}

func envWith(base, pairs []string) []string {
	env := make([]string, 0, len(base)+len(pairs))
	env = append(env, base...)
	return append(env, pairs...)
}

// ---------------------------------------------------------------------------
// Chromium / Chrome 启动参数
// ---------------------------------------------------------------------------

// desktopProxyFlagURL 返回写入 --proxy-server 的 URL（HTTP 优先，SOCKS 回退）。
func desktopProxyFlagURL(http, socks *EndpointState) string {
	if u := endpointURL("http", http); u != "" {
		return u
	}
	return endpointURL("socks5", socks)
}

func setBrowserProxyFlag(flagURL string) error {
	var errs []error
	for _, p := range chromiumFlagFiles() {
		content, err := os.ReadFile(p)
		if err != nil && !os.IsNotExist(err) {
			errs = append(errs, err)
			continue
		}
		if err := writeFileAtomic(p, withProxyFlag(string(content), flagURL), 0o644); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

func clearBrowserProxyFlags() error {
	var errs []error
	for _, p := range chromiumFlagFiles() {
		if err := removeBrowserProxyFlag(p); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// restoreBrowserFlagFile 恢复 Chromium 文件：若快照前文件已存在则只移除
// proxyctl 写入的行；若文件是 proxyctl 新建的则删除空文件。
func restoreBrowserFlagFile(path string, existedBefore bool) error {
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return nil
	}
	content, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	cleaned := withoutProxyFlag(string(content))
	if !existedBefore && strings.TrimSpace(cleaned) == "" {
		return os.Remove(path)
	}
	return writeFileAtomic(path, cleaned, 0o644)
}

func removeBrowserProxyFlag(path string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	cleaned := withoutProxyFlag(string(content))
	if strings.TrimSpace(cleaned) == "" {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	return writeFileAtomic(path, cleaned, 0o644)
}

// withProxyFlag 返回加入 --proxy-server 行后的内容（保留原有其他行）。
func withProxyFlag(content, flagURL string) string {
	cleaned := withoutProxyFlag(content)
	if cleaned != "" && !strings.HasSuffix(cleaned, "\n") {
		cleaned += "\n"
	}
	return cleaned + proxyFlagPrefix + flagURL + "\n"
}

// withoutProxyFlag 移除内容中全部 --proxy-server 行（允许行首空白）。
func withoutProxyFlag(content string) string {
	var b strings.Builder
	for _, line := range strings.SplitAfter(content, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), proxyFlagPrefix) {
			continue
		}
		b.WriteString(line)
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// 通用文件写入
// ---------------------------------------------------------------------------

// writeFileAtomic 原子写入文件（先写同目录临时文件再 rename）。
func writeFileAtomic(path, content string, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".proxyctl-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	cleanup := func() {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
	}
	if err := tmp.Chmod(perm); err != nil {
		cleanup()
		return err
	}
	if _, err := tmp.WriteString(content); err != nil {
		cleanup()
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	return nil
}
