//go:build linux

package proxy

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseGValue(t *testing.T) {
	tests := []struct {
		raw, want string
	}{
		{"'manual'", "manual"},
		{"'none'", "none"},
		{"7892", "7892"},
		{"0", "0"},
		{"'10.10.10.113'", "10.10.10.113"},
	}
	for _, tt := range tests {
		if got := parseGValue(tt.raw); got != tt.want {
			t.Errorf("parseGValue(%q) = %q, want %q", tt.raw, got, tt.want)
		}
	}
}

func TestParseGStringList(t *testing.T) {
	got := parseGStringList("['localhost', '127.0.0.1', '::1']")
	want := []string{"localhost", "127.0.0.1", "::1"}
	if len(got) != len(want) {
		t.Fatalf("parseGStringList = %#v", got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("parseGStringList[%d] = %q, want %q", i, got[i], want[i])
		}
	}
	if got := parseGStringList("[]"); got != nil {
		t.Errorf("空数组应返回 nil，got %#v", got)
	}
}

func TestSessionEnvRoundTrip(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	vars := sessionEnvVars(
		&EndpointState{Enabled: true, Host: "10.10.10.113", Port: "7892"},
		&EndpointState{Enabled: true, Host: "10.10.10.113", Port: "7892"},
	)
	if err := writeSessionEnv(vars); err != nil {
		t.Fatalf("writeSessionEnv: %v", err)
	}
	data, err := os.ReadFile(sessionEnvPath())
	if err != nil {
		t.Fatalf("会话环境文件未写入: %v", err)
	}
	text := string(data)
	if !strings.Contains(text, sessionEnvMarker) {
		t.Errorf("缺少受管标记:\n%s", text)
	}
	if !strings.Contains(text, "http_proxy=http://10.10.10.113:7892") {
		t.Errorf("缺少 http_proxy:\n%s", text)
	}

	info, ok := readSessionEnvInfo()
	if !ok {
		t.Fatal("readSessionEnvInfo 未识别受管文件")
	}
	if got := info.HTTPProxyURL(); got != "http://10.10.10.113:7892" {
		t.Errorf("HTTPProxyURL = %q", got)
	}
	if got := info.SOCKSPProxyURL(); got != "socks5h://10.10.10.113:7892" {
		t.Errorf("SOCKSPProxyURL = %q", got)
	}
}

func TestSessionEnvOnlyRemovesManagedFile(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())

	// 用户自建文件：不删除。
	if err := os.MkdirAll(filepath.Dir(sessionEnvPath()), 0o755); err != nil {
		t.Fatal(err)
	}
	userContent := "http_proxy=http://example.invalid:8080\n"
	if err := os.WriteFile(sessionEnvPath(), []byte(userContent), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := removeSessionEnv(); err != nil {
		t.Fatalf("removeSessionEnv: %v", err)
	}
	if data, err := os.ReadFile(sessionEnvPath()); err != nil || string(data) != userContent {
		t.Fatalf("用户自建文件被删除或修改: %q, %v", data, err)
	}

	// proxyctl 受管文件：删除。
	if err := writeSessionEnv(sessionEnvVars(
		&EndpointState{Enabled: true, Host: "127.0.0.1", Port: "7890"},
		nil,
	)); err != nil {
		t.Fatal(err)
	}
	if err := removeSessionEnv(); err != nil {
		t.Fatalf("removeSessionEnv(managed): %v", err)
	}
	if _, err := os.Stat(sessionEnvPath()); !os.IsNotExist(err) {
		t.Fatalf("受管文件删除后仍存在: %v", err)
	}
}

func TestRestoreRemovesEnvFileWhenSnapshotHadNone(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	if err := writeSessionEnv(sessionEnvVars(
		&EndpointState{Enabled: true, Host: "127.0.0.1", Port: "7890"},
		nil,
	)); err != nil {
		t.Fatal(err)
	}

	snap := SystemSnapshot{Linux: &LinuxSnapshot{}}
	if err := RestoreSystem(snap); err != nil {
		t.Fatalf("RestoreSystem: %v", err)
	}
	if _, err := os.Stat(sessionEnvPath()); !os.IsNotExist(err) {
		t.Fatal("快照中环境文件不存在时，restore 应删除 proxyctl 受管文件")
	}
}

func TestLegacyManagedMarker(t *testing.T) {
	if !isManagedEnvText("# Generated by proxy-on.sh. Use proxy-on.sh/proxy-off.sh to change.\nhttp_proxy=...") {
		t.Error("旧 proxy-on.sh 标记应被识别为受管文件")
	}
	if isManagedEnvText("# user file\nhttp_proxy=...") {
		t.Error("用户自建文件不应被识别为受管文件")
	}
}

func TestChromiumFlagEdit(t *testing.T) {
	orig := "--user-data-dir=/tmp/x\n# comment\n"
	got := withProxyFlag(orig, "http://127.0.0.1:7892")
	if !strings.Contains(got, "--proxy-server=http://127.0.0.1:7892\n") {
		t.Errorf("缺少 --proxy-server 行:\n%s", got)
	}
	if !strings.Contains(got, "--user-data-dir=/tmp/x") {
		t.Errorf("原有内容丢失:\n%s", got)
	}

	cleaned := withoutProxyFlag(got)
	if cleaned != orig {
		t.Errorf("withoutProxyFlag 后内容不一致:\n%q\nwant:\n%q", cleaned, orig)
	}

	// 移除已有行后追加新地址不会产生重复行。
	again := withProxyFlag(got, "http://127.0.0.1:7890")
	if n := strings.Count(again, "--proxy-server="); n != 1 {
		t.Errorf("--proxy-server 出现 %d 次:\n%s", n, again)
	}
}

func TestRestoreBrowserFlagFiles(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "chromium-flags.conf")

	// proxyctl 新建的文件：restore 后应删除。
	if err := writeFileAtomic(path, "--proxy-server=http://127.0.0.1:7892\n", 0o644); err != nil {
		t.Fatal(err)
	}
	if err := restoreBrowserFlagFile(path, false); err != nil {
		t.Fatalf("restoreBrowserFlagFile(created): %v", err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatal("proxyctl 新建的 Chromium 文件 restore 后应删除")
	}

	// restore 前已存在的文件：保留文件，只移除我们写入的行。
	userFlags := "--disable-features=DarkMode\n"
	if err := os.WriteFile(path, []byte(withProxyFlag(userFlags, "http://127.0.0.1:7892")), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := restoreBrowserFlagFile(path, true); err != nil {
		t.Fatalf("restoreBrowserFlagFile(existed): %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != userFlags {
		t.Errorf("已存在文件的用户内容未保留: %q", data)
	}
}
